<?php


  namespace App\Http\Controllers\Auth;


  use Illuminate\Auth\EloquentUserProvider;

  class CustomUserProvider extends EloquentUserProvider {
    public function retrieveByCredentials(array $credentials) {

      return parent::retrieveByCredentials($credentials); // TODO: Change the autogenerated stub
    }

  }