<?php

namespace Tests\Feature;

use App\Bank;
use App\Currency;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

/**
 * Class UserTest
 * @package Tests\Feature
 */
class BanksTest extends TestCase
{
    use RefreshDatabase;
    /**
     * @test
     */
    public function aUserCanGetVenezuelanBanks(){
        $this->actingAsCoordinator();
        $currency = factory(Currency::class)->create(['name'=>'Bolivar Soberano']);
        factory(Bank::class,4)->create([
            'currency_id'=>$currency->id
        ]);
        //remember on currency creation a bank is autogenerated called cash
        $this->getJson(route('venezuelan_banks'))->assertStatus(200)->assertJsonCount(5);
    }
}

