<?php

    namespace Tests\Feature;

    use App\Bank;
    use App\Currency;
    use Tests\TestCase;
    use Illuminate\Foundation\Testing\RefreshDatabase;

    /**
     * Class UserTest
     * @package Tests\Feature
     */
    class BanksTest extends TestCase
    {
        use RefreshDatabase;

        /**
         * @test
         */
        public function onlyCoordinatorCanSeeVenezuelanBanksList()
        {
            $currency = factory(Currency::class)->create(['name' => 'Bolivar Soberano']);
            factory(Bank::class, 4)->create([
                'currency_id' => $currency->id
            ]);
            $this->getJson(route('venezuelan_banks'))->assertStatus(401);
            $this->actingAsReceiver();
            $this->getJson(route('venezuelan_banks'))->assertStatus(403);
            $this->actingAsClient();
            $this->getJson(route('venezuelan_banks'))->assertStatus(403);
            $this->actingAsVenezuelanOperator();
            $this->getJson(route('venezuelan_banks'))->assertStatus(403);
            $this->actingAsForeignOperator();
            $this->getJson(route('venezuelan_banks'))->assertStatus(403);
            $this->actingAsCoordinator();
            $this->getJson(route('venezuelan_banks'))->assertStatus(200)->assertJsonCount(5);
            //remember on currency creation a bank is autogenerated called cash
        }

        /**
         * @test
         */
        public function onlyCoordinatorCanSeeAllBanksList()
        {
            $this->getJson(route('banks'))->assertStatus(401);
            $this->actingAsReceiver();
            $this->getJson(route('banks'))->assertStatus(403);
            $this->actingAsClient();
            $this->getJson(route('banks'))->assertStatus(403);
            $this->actingAsVenezuelanOperator();
            $this->getJson(route('banks'))->assertStatus(403);
            $this->actingAsForeignOperator();
            $this->getJson(route('banks'))->assertStatus(403);
            $this->actingAsCoordinator();
            $this->getJson(route('banks'))->assertStatus(200);
        }

        /**
         * @test
         */
        public function onlyCoordinatorCanSeeBanksByCountryList()
        {
            $currency = factory(Currency::class)->create();
            $this->getJson(route('country_banks', $currency->id))->assertStatus(401);
            $this->actingAsReceiver();
            $this->getJson(route('country_banks', $currency->id))->assertStatus(403);
            $this->actingAsClient();
            $this->getJson(route('country_banks', $currency->id))->assertStatus(403);
            $this->actingAsVenezuelanOperator();
            $this->getJson(route('country_banks', $currency->id))->assertStatus(403);
            $this->actingAsForeignOperator();
            $this->getJson(route('country_banks', $currency->id))->assertStatus(200);
            $this->actingAsCoordinator();
            $this->getJson(route('country_banks', $currency->id))->assertStatus(200);
        }

        /**
         * @test
         */
        public function onlyCoordinatorCanCreateBanks()
        {
            $currency = factory(Currency::class)->create();
            $bankArray = ['name' => 'Banco Prueba',
                'currency_id' => $currency->id
            ];
            $this->postJson(route('save_bank'), $bankArray)->assertStatus(401);
            $this->actingAsReceiver();
            $this->postJson(route('save_bank'), $bankArray)->assertStatus(403);
            $this->actingAsClient();
            $this->postJson(route('save_bank'), $bankArray)->assertStatus(403);
            $this->actingAsVenezuelanOperator();
            $this->postJson(route('save_bank'), $bankArray)->assertStatus(403);
            $this->actingAsForeignOperator();
            $this->postJson(route('save_bank'), $bankArray)->assertStatus(403);
            $this->actingAsCoordinator();
            $this->postJson(route('save_bank'), $bankArray)->assertStatus(201);
        }
    }

